-- Notifications System for StartiGeniX
-- Creates notifications table and triggers for automatic notification generation

-- 1. NOTIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  actor_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('upvote', 'comment', 'reply', 'follow', 'mention')),
  post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
  comment_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE,
  message TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Users can only see their own notifications
CREATE POLICY "notifications_select_own" ON public.notifications 
  FOR SELECT USING (auth.uid() = user_id);

-- System inserts notifications (via triggers with SECURITY DEFINER)
CREATE POLICY "notifications_insert_system" ON public.notifications 
  FOR INSERT WITH CHECK (true);

-- Users can update their own notifications (mark as read)
CREATE POLICY "notifications_update_own" ON public.notifications 
  FOR UPDATE USING (auth.uid() = user_id);

-- Users can delete their own notifications
CREATE POLICY "notifications_delete_own" ON public.notifications 
  FOR DELETE USING (auth.uid() = user_id);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS notifications_user_id_idx ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS notifications_created_at_idx ON public.notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS notifications_is_read_idx ON public.notifications(user_id, is_read);

-- 2. TRIGGER FUNCTION FOR UPVOTE NOTIFICATIONS
CREATE OR REPLACE FUNCTION public.create_upvote_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  post_owner_id UUID;
  post_title TEXT;
BEGIN
  -- Get the post owner and title
  SELECT user_id, title INTO post_owner_id, post_title
  FROM public.posts
  WHERE id = NEW.post_id;

  -- Don't notify if user upvotes their own post
  IF post_owner_id IS NOT NULL AND post_owner_id != NEW.user_id THEN
    INSERT INTO public.notifications (user_id, actor_id, type, post_id, message)
    VALUES (
      post_owner_id,
      NEW.user_id,
      'upvote',
      NEW.post_id,
      'liked your post' || CASE WHEN post_title IS NOT NULL THEN ': "' || LEFT(post_title, 50) || '"' ELSE '' END
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_upvote_notification ON public.upvotes;

CREATE TRIGGER on_upvote_notification
  AFTER INSERT ON public.upvotes
  FOR EACH ROW
  EXECUTE FUNCTION public.create_upvote_notification();

-- 3. TRIGGER FUNCTION FOR COMMENT NOTIFICATIONS
CREATE OR REPLACE FUNCTION public.create_comment_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  post_owner_id UUID;
  post_title TEXT;
  parent_comment_owner_id UUID;
BEGIN
  -- Get the post owner and title
  SELECT user_id, title INTO post_owner_id, post_title
  FROM public.posts
  WHERE id = NEW.post_id;

  -- Check if this is a reply to another comment
  IF NEW.parent_id IS NOT NULL THEN
    -- Get the parent comment owner
    SELECT user_id INTO parent_comment_owner_id
    FROM public.comments
    WHERE id = NEW.parent_id;

    -- Notify the parent comment owner (if not replying to self)
    IF parent_comment_owner_id IS NOT NULL AND parent_comment_owner_id != NEW.user_id THEN
      INSERT INTO public.notifications (user_id, actor_id, type, post_id, comment_id, message)
      VALUES (
        parent_comment_owner_id,
        NEW.user_id,
        'reply',
        NEW.post_id,
        NEW.id,
        'replied to your comment: "' || LEFT(NEW.content, 50) || CASE WHEN LENGTH(NEW.content) > 50 THEN '...' ELSE '' END || '"'
      );
    END IF;
  END IF;

  -- Notify the post owner about the comment (if not commenting on own post and not already notified as reply owner)
  IF post_owner_id IS NOT NULL 
     AND post_owner_id != NEW.user_id 
     AND (parent_comment_owner_id IS NULL OR parent_comment_owner_id != post_owner_id) THEN
    INSERT INTO public.notifications (user_id, actor_id, type, post_id, comment_id, message)
    VALUES (
      post_owner_id,
      NEW.user_id,
      'comment',
      NEW.post_id,
      NEW.id,
      'commented on your post' || CASE WHEN post_title IS NOT NULL THEN ' "' || LEFT(post_title, 30) || '"' ELSE '' END || ': "' || LEFT(NEW.content, 40) || CASE WHEN LENGTH(NEW.content) > 40 THEN '...' ELSE '' END || '"'
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_comment_notification ON public.comments;

CREATE TRIGGER on_comment_notification
  AFTER INSERT ON public.comments
  FOR EACH ROW
  EXECUTE FUNCTION public.create_comment_notification();

-- 4. FUNCTION TO MARK ALL NOTIFICATIONS AS READ
CREATE OR REPLACE FUNCTION public.mark_all_notifications_read(p_user_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.notifications
  SET is_read = TRUE
  WHERE user_id = p_user_id AND is_read = FALSE;
END;
$$;

-- 5. FUNCTION TO GET UNREAD NOTIFICATION COUNT
CREATE OR REPLACE FUNCTION public.get_unread_notification_count(p_user_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  count_result INTEGER;
BEGIN
  SELECT COUNT(*)::INTEGER INTO count_result
  FROM public.notifications
  WHERE user_id = p_user_id AND is_read = FALSE;
  
  RETURN count_result;
END;
$$;
